# Generated by Django 5.2 on 2025-04-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='defense',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='fighter',
            name='grappling',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='fighter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fighters/photos/'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='speed',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='fighter',
            name='stamina',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='fighter',
            name='striking',
            field=models.IntegerField(default=50),
        ),
    ]
