# Generated by Django 5.2 on 2025-04-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0002_fighter_defense_fighter_grappling_fighter_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='created_at',
        ),
        migrations.AddField(
            model_name='fighter',
            name='detailed_stats',
            field=models.JSONField(blank=True, default=dict, help_text="Stats in JSON format: {'Knockouts': 19, 'Submissions': 1, ...}"),
        ),
        migrations.AddField(
            model_name='fighter',
            name='recent_fights',
            field=models.TextField(blank=True, help_text="Recent fights as newline-separated entries: 'Oct 2020: vs. Khabib Nurmagomedov (Loss)'"),
        ),
        migrations.AddField(
            model_name='fighter',
            name='video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID for fight highlights (e.g., dQw4w9WgXcQ)', max_length=50),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='grappling',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='stamina',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='striking',
            field=models.IntegerField(default=0),
        ),
    ]
