# Generated by Django 5.2 on 2025-04-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0004_alter_fighter_bio_alter_fighter_defense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
