# Generated by Django 5.2 on 2025-04-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0005_fighter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='p4p_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='weight_class',
            field=models.CharField(blank=True, choices=[('FLYWEIGHT', 'Flyweight (125 lbs)'), ('BANTAMWEIGHT', 'Bantamweight (135 lbs)'), ('FEATHERWEIGHT', 'Featherweight (145 lbs)'), ('LIGHTWEIGHT', 'Lightweight (155 lbs)'), ('WELTERWEIGHT', 'Welterweight (170 lbs)'), ('MIDDLEWEIGHT', 'Middleweight (185 lbs)'), ('LIGHT_HEAVYWEIGHT', 'Light Heavyweight (205 lbs)'), ('HEAVYWEIGHT', 'Heavyweight (265 lbs)')], max_length=20),
        ),
    ]
