# Generated by Django 5.2 on 2025-04-25 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0006_fighter_p4p_ranking_fighter_weight_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FightCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('predicted_winner', models.CharField(blank=True, max_length=100)),
                ('fighter1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fightcard_fighter1', to='fighters.fighter')),
                ('fighter2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fightcard_fighter2', to='fighters.fighter')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fighters.fighter')),
                ('fight_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='fighters.fightcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fight_card', 'user')},
            },
        ),
    ]
